apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo-preview-only
spec:
  ingressClassName: nginx
  rules:
  - host: preview.test-rollout.k8s.cagip.hackervaillant.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canary-demo-preview
            port:
              number: 80
